name: Build and Test Nginx TorBlocker

permissions:
  contents: read

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu: [jammy, noble]
        nginx_version: [1.27.0, 1.28.0]
    env:
      NGINX_VERSION: ${{ matrix.nginx_version }}
      UBUNTU_CODENAME: ${{ matrix.ubuntu }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget gcc libpcre3-dev zlib1g-dev

      - name: Download and extract Nginx source
        run: |
          mkdir -p nginx-sources/${{ matrix.nginx_version }}/${{ matrix.ubuntu }}
          cd nginx-sources/${{ matrix.nginx_version }}/${{ matrix.ubuntu }}
          wget -nv https://nginx.org/download/nginx-${{ matrix.nginx_version }}.tar.gz
          tar xzf nginx-${{ matrix.nginx_version }}.tar.gz

      - name: Build dynamic module with Nginx source
        run: |
          cd nginx-sources/${{ matrix.nginx_version }}/${{ matrix.ubuntu }}/nginx-${{ matrix.nginx_version }}
          SRC_PATH="$GITHUB_WORKSPACE/src"
          echo "Using src path: $SRC_PATH"
          ./configure --add-dynamic-module=$SRC_PATH
          make modules

      - name: Check module output
        run: |
          test -f nginx-sources/${{ matrix.nginx_version }}/${{ matrix.ubuntu }}/nginx-${{ matrix.nginx_version }}/objs/ngx_http_torblocker_module.so
          file nginx-sources/${{ matrix.nginx_version }}/${{ matrix.ubuntu }}/nginx-${{ matrix.nginx_version }}/objs/ngx_http_torblocker_module.so
